@startuml
!theme mars
component container  [
Docker container
===
{{
    artifact microservice as "spring-boot-microservice.jar"
}}
---
{{
    component JVM as "Java -e.g. OpenJDK -"
}}
---
{{
    component Glibc as "Glibc /  Musl (Linux stdlib)"
}}
]
@enduml