@startuml
!theme toy

package Deployment {


     component rs as "ReplicaSet"{
    
        component pod

        component pod2 

        component pod3 as "pod..."

        
    }

    database PersistentVolume as "PersistentVolume"
}

boundary service as "service <<network lb>>"

service ...> pod
service ...> pod2
service ...> pod3

pod ..> PersistentVolume
pod2 ..> PersistentVolume
pod3 ..> PersistentVolume

@enduml
